PHSach/Models/Inventory_Book.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Book
    {
        public int id { get; set; }
        public int Book_id { get; set; }
        public int Quantity { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Book Book { get; set; }
    }
}

PHSach/Controllers/Inventory_BookController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PHSach.Models;

namespace PHSach.Controllers
{
    public class Inventory_BookController : Controller
    {
        private PhatHanhSachEntities db = new PhatHanhSachEntities();

        public ActionResult Index()
        {
            var books = from f in (from a in (from b in db.Inventory_Book.Include(b => b.Book) group b by b.Book_id into gr select new { book_id = gr.Key, updated_date = gr.Max(x => x.UpdatedDate) })
                                   from d in db.Inventory_Book
                                   orderby d.UpdatedDate descending
                                   where a.book_id == d.Book_id && a.updated_date == d.UpdatedDate
                                   select d).Include(f => f.Book)
                        select f;

            ViewBag.listbook = books.ToList();
            return View();
        }
        // Bảo - 20/10/2017
        // Bảo 20/10/2017
        [HttpPost]
        public JsonResult HistoryInventory(string masach, string choosedate)
        {
            try
            {
                int id = int.Parse(masach);
                DateTime date = DateTime.Parse(choosedate);
                date = new DateTime(date.Year, date.Month, date.Day, 23, 59, 59);
                var inventory_Book = db.Inventory_Book.Include(c => c.Book)
                    .Where(c => c.Book_id == id && c.UpdatedDate <= date)
                    .OrderByDescending(c => c.UpdatedDate)
                    .Select(c => c).FirstOrDefault();
                if (inventory_Book != null)
                {
                    return Json(new { id = inventory_Book.Book_id, bookname = inventory_Book.Book.Book_name, quantity = inventory_Book.Quantity, updatedate = (inventory_Book.UpdatedDate)?.ToString("dd / MM / yyyy HH:mm:ss") });
                }
            }
            catch
            {
                return Json(new { });
            }
            return Json(new { });
        }
        // Bảo 20/10/2017
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PHSach/Views/Inventory_Book/Index.cshtml
@{
    ViewBag.Title = "Index";
}

    <form class="form-inline">
        <div class="col-md-12 panel panel-primary">
            <div class="panel-heading">Tìm kiếm lịch sử tồn kho</div>
            <div class="panel-body ">
                <div class="col-md-4 masachtk">
                    <label for="masach">Mã sách :</label>
                    <input class="form-control" id="masach" type="text" placeholder="nhập mã sách">
                </div>
                <div class="col-md-4">
                    <label for="choosedate"> Chọn ngày : </label>
                    <input type="date" class="form-control" id="choosedate">
                </div>
                <div class="col-md-2">
                    <button type="button" class="btn btn-info btnseach"><i class="fa fa-search"></i> Tìm kiếm </button>
                </div>
                <div class="col-md-2">
                    <button type="button" class="btn btn-info btnrefresh"><i class="fa fa-refresh"></i> Làm mới </button>
                </div>
            </div>
        </div>
    </form>
    <div class="col-md-12 panel panel-primary">
        <div class="panel-heading">Kết quả tìm kiếm</div>
            <div class="noti alert alert-info" style="margin-top:10px;display:none" ></div>
             <div class="panel-body">
                <form class="form-inline">
                    <div class="col-md-12  div_Masach">
                        <div class="col-sm-4 form-group">
                            <label for="book_id"><b>Mã sách:</b></label>
                            <input class="form-control" id="book_id" type="text" disabled value="" >
                        </div>
                        <div class="col-sm-8 form-group" >
                            <label for="book_name"><b>Tên sách :</b></label>
                            <input class="form-control" id="book_name" type="text" disabled value="" style="width:400px">
                        </div>
                     </div>
                    <div class="col-md-12 div_soluong" style="margin-top:10px;" >
                        <div class="col-sm-4 form-group">
                            <label for="quantity"><b>Số lượng tồn :</b></label>
                            <input class="form-control" id="quantity" type="number" disabled value="" style="width:140px;">
                        </div>
                        <div class="col-sm-8 form-group" >
                            <label for="updatedate"><b>Ngày cập nhật gần nhất :</b></label>
                            <input class="form-control" id="updatedate" type="text" disabled value="" style="width:302px;">
                        </div>
                      </div>
                </form>
            </div>
        </div>
    <div class="col-md-12 panel panel-info">
        <div class="panel-heading">Tồn Kho</div>
        <div class="panel-body">

            <div class="col-md-12 div-inventory">
                <table class="table table-bordered table-hover table-inventory" >
                    <thead>
                        <tr>
                            <th >Mã sách</th>
                            <th>Tên sách</th>
                            <th>Số lượng tồn</th>
                            <th>Ngày cập nhật mới nhất</th>
                        </tr>
                    </thead>
                    <tbody>
                        
                            @foreach (var item in (IList<PHSach.Models.Inventory_Book>)ViewBag.listbook)
                            {
                                <tr>
                                    <td>@item.Book_id</td>
                                    <td>@item.Book.Book_name</td>
                                    <td>@item.Quantity</td>
                                    <td>@item.UpdatedDate.Value.ToString("dd/MM/yyyy HH:mm:ss")</td> 
                                </tr>
                            }
                    </tbody>
                </table>
            </div>
        </div>
</div>
<script>
  $(document).ready(function () {
        $('.btnseach').click( function () {
            var masach = $('#masach').val();
            var date = $('#choosedate').val();
            $('.noti').hide();
            if (masach.length === 0)
            {
                alert("Nhập mã sách cần tìm !");

            }

            else
            {
                if (date.length === 0)
                {
                    alert("Nhập ngày cần tìm !");
                }
                else
                {
                    $.ajax({
                        url: "/Inventory_Book/HistoryInventory",
                        data: { masach: masach, choosedate: date },
                        dataType: "json",
                        type: "POST",
                        success: function (data) {
                            if (typeof(data['id'])!== 'undefined')
                            {
                                $('#book_id').val(data['id']);
                                $('#book_name').val(data['bookname']);
                                $('#quantity').val(data['quantity']);
                                $('#updatedate').val(data['updatedate']);
                            }
                            else
                            {
                                $('.noti').html(" Không tìm thấy dữ liệu theo yêu cầu ! ");
                                $('.noti').css('display', 'block');
                                $('#book_id').val("");
                                $('#book_name').val("");
                                $('#quantity').val("");
                                $('#updatedate').val("");
                            }
                        },
                        error: function (a, b, c) {

                        }
                    });
                }

            }

        });
        $('.btnrefresh').click(function () {
            $('#book_id').val("");
            $('#book_name').val("");
            $('#quantity').val("");
            $('#updatedate').val("");
            $('.noti').html("");
            $('.noti').css('display', 'none');
            $('#masach').val("");
            $('#choosedate').val("");
        });

  });
</script>

PHSach/Views/Inventory_Book/ThongKe.cshtml
@{
    ViewBag.Title = "ThongKe";
}

<h2>Thống kê tồn kho</h2>

<p>
    <a class="btn btn-primary btnThemPhieuNhap" href="~/Inventory_Book/Index">Quay lại</a>
</p>

@using (Html.BeginForm("ThongKe", "Inventory_Book", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />

        <div class="form-group col-sm-10">
            <div class="col-sm-6">
                <label for="disabledInput">Chọn ngày thống kê</label>
                <div class='input-group date' id="myDate">
                    <input id="date" name="date" type="date" class="form-control col-md-7 col-xs-12" />
                </div>
            </div>


            <div class="form-group col-sm-10">
                <div class="col-sm-6">
                    <label for="disabledInput">Chọn sách</label>
                    @Html.DropDownList("danhsach", null, htmlAttributes: new { @class = "form-control" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thống kê" class="btn btn-default" />
            </div>
        </div>
    </div>
    <br /><br />
        <div class="form-group">
 
            <div class="col-md-offset-2 col-md-10">
                @if(ViewBag.ketqua != null)
                {
                    <b>@ViewBag.ketqua</b>
                }
            </div>
        </div>
}