PHSach/Models/Bill_Export.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill_Export
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bill_Export()
        {
            this.Detail_Bill_Export = new HashSet<Detail_Bill_Export>();
        }
    
        public int Bill_Export_id { get; set; }
        public int Agency_id { get; set; }
        public double Total { get; set; }
        public string Recipients { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Agency Agency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detail_Bill_Export> Detail_Bill_Export { get; set; }
    }
}

PHSach/Controllers/Bill_ExportController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PHSach.Models;

namespace PHSach.Controllers
{
    public class Bill_ExportController : Controller
    {
        private PhatHanhSachEntities db = new PhatHanhSachEntities();

        // GET: Bill_Export
        public ActionResult Index()
        {
            var bill_Export = db.Bill_Export.Include(b => b.Agency);
            return View(bill_Export.ToList());
        }

        public ActionResult Deletectpx(int bookid)
        {
            var list = (List<Detail_Bill_Export>)Session["ctphieuxuat"];
            list.RemoveAll(p => p.Book_id == bookid);
            return RedirectToAction("ThemChiTietPhieuXuat");
        }

        // GET: Bill_Export/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bill_Export bill_Export = db.Bill_Export.Find(id);
            var a = (from b in db.Detail_Bill_Export
                     where b.Bill_Export_id == id
                     select b).ToList();
            ViewBag.ctpx = a;
            if (bill_Export == null)
            {
                return HttpNotFound();
            }
            return View(bill_Export);
        }

        // GET: Bill_Export/Create
        public ActionResult Create()
        {
            ViewBag.Agency_id = new SelectList(db.Agencies, "Agency_id", "Agency_name");
            return View();
        }

        // POST: Bill_Export/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Bill_Export_id,Agency_id,Total,Recipients,CreatedDate")] Bill_Export bill_Export)
        {
            if (ModelState.IsValid)
            {
                bill_Export.CreatedDate = DateTime.Now;
                var tempbillexport = bill_Export;
                Session["ctphieuxuat"] = new List<Detail_Bill_Export>();
                Session["PhieuXuat"] = bill_Export;
                return RedirectToAction("ThemChiTietPhieuXuat");
            }

            ViewBag.Agency_id = new SelectList(db.Agencies, "Agency_id", "Agency_name", bill_Export.Agency_id);
            return View(bill_Export);
        }

        [HttpGet]
        public ActionResult ThemChiTietPhieuXuat()
        {
            var lstb = db.Books;
            List<Book> lstbtk = new List<Book>();
            foreach (var item in lstb)
            {
                Inventory_Book tonkhosach = db.Inventory_Book.OrderByDescending(m => m.id).FirstOrDefault(m => m.Book_id == item.Book_id);
                if (tonkhosach != null)
                {
                    if (tonkhosach.Quantity > 0)
                    {
                        Book bk = db.Books.FirstOrDefault(m => m.Book_id == tonkhosach.Book_id);
                        lstbtk.Add(bk);
                    }
                }
            }

            ViewBag.sach = new SelectList(lstbtk, "Book_id", "Book_name");
            //var phieuxuat = (Bill_Export)TempData["PhieuXuat"];
            return View();
        }

        [HttpPost]
        public ActionResult ThemChiTietPhieuXuat(FormCollection chitiet)
        {
            ViewBag.sach = new SelectList(db.Books, "Book_id", "Book_name");
            ViewBag.loi = null;
            if (Request.Form["add"] != null)
            {
                if (ModelState.IsValid)
                {
                    bool check = true;
                    foreach (var ctpx in (List<Detail_Bill_Export>)Session["ctphieuxuat"])
                    {
                        if (ctpx.Book_id == Int32.Parse(chitiet["sach"].ToString()))
                        {
                            check = false;
                            ViewBag.loi = "Sách đã được thêm vào phiếu trước đó";                           
                            break;
                        }
                    }
                    if (check)
                    {
                        //kiểm tra trong kho có sách đó hay không
                        if (chitiet["sach"] == null)
                        {
                            ViewBag.loi = "Không tồn tại sách để xuất";
                            goto baoloi;
                        }
                        //khai báo để tìm nợ của đại lý đó
                        Bill_Export test1 = (Bill_Export)Session["PhieuXuat"];
                        Debt_Agency test2 = db.Debt_Agency.OrderByDescending(m => m.id).FirstOrDefault(m => m.Agency_id == (int)test1.Agency_id);
                        //lấy số lượng nhâp từ form và lấy tồn kho của sách vừa nhập
                        var sach = db.Books.Find(Int32.Parse(chitiet["sach"].ToString()));
                        int soluong = Int32.Parse(chitiet["soluong"].ToString());
                        Inventory_Book tonkho1 = db.Inventory_Book.OrderByDescending(m => m.id).FirstOrDefault(m => m.Book_id == (int)sach.Book_id);

                        //kiểm tra mã sách
                        if (sach == null)
                        {
                            ViewBag.loi = "Mã sách không tồn tại";
                            goto baoloi;
                        }
                        else
                        {
                            //kiểm tra tồn kho
                            if (tonkho1 == null)
                            {
                                ViewBag.loi = "Không có tồn kho";
                                goto baoloi;
                            }
                            else
                            {
                                //nếu tòn kho <= 0
                                if (tonkho1.Quantity <= 0)
                                {
                                    ViewBag.loi = "Sách đã hết trong kho";
                                    goto baoloi;
                                }
                                else
                                {
                                    //kiểm tra điều kiện vượt quá số lượng trong kho
                                    if (tonkho1.Quantity < soluong)
                                    {
                                        ViewBag.loi = "Số lượng sách không đủ để xuất";
                                        goto baoloi;
                                    }
                                    else
                                    {
                                        //kiểm tra số lượng nhập vào phải lớn 0
                                        if(soluong > 0)
                                        {
                                            Detail_Bill_Export ctpx = new Detail_Bill_Export();
                                            ctpx.Bill_Export_id = (db.Bill_Export.Max(u => (int?)u.Bill_Export_id) != null ? db.Bill_Export.Max(u => u.Bill_Export_id) : 0) + 1;// db.Bill_Export.Count() + 1;
                                            ctpx.Book_id = Int32.Parse(chitiet["sach"].ToString());
                                            ctpx.Quantity = Int32.Parse(chitiet["soluong"].ToString());
                                            ctpx.Cost = double.Parse(db.Books.Find(ctpx.Book_id).Cost_Export.ToString());
                                            ctpx.Total = ctpx.Quantity * ctpx.Cost;
                                            //kiểm tra tổng tiền của phiếu có lớn hơn số nợ hay không
                                            double checktien = 0;
                                            foreach (var checktest in (List<Detail_Bill_Export>)Session["ctphieuxuat"])
                                            {
                                                checktien += checktest.Total;
                                            }
                                            checktien += ctpx.Total;
                                            if (test2 == null || (test2 != null && test2.debt > 0 && test2.debt >= checktien) || test2.debt == 0)
                                            {
                                                ((List<Detail_Bill_Export>)Session["ctphieuxuat"]).Add(ctpx);
                                            }
                                            else
                                            {
                                                ViewBag.loi = "Vượt quá số nợ cho phép, mức nợ hiện tại là: " + test2.debt;
                                                goto baoloi;
                                            }
                                        }
                                        else
                                        {
                                            ViewBag.loi = "Nhập số lượng lớn hơn 0";
                                            goto baoloi;
                                        }
                                        
                                    }
                                }
                            }
                        }
                        return RedirectToAction("ThemChiTietPhieuXuat");
                    }
                    else
                    {
                       
                    }
                }
            }
            else if (Request.Form["create"] != null)
            {
                if (ModelState.IsValid)
                {
                    if (((List<Detail_Bill_Export>)Session["ctphieuxuat"]).Count == 0)
                    {

PHSach/Views/Bill_Export/Create.cshtml
@model PHSach.Models.Bill_Export

@{
    ViewBag.Title = "Create";
}

<h2>Tạo phiếu xuất sách</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-horizontal">
        <hr />

        <div class="form-group col-sm-10">
            <div class="col-sm-6">
                <label for="disabledInput">Tên Đại Lý:</label>
                @Html.DropDownList("Agency_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Agency_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-sm-10">
            <div class="col-md-6">
                <label for="disabledInput">Người nhận hàng:</label>
                @Html.EditorFor(model => model.Recipients, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Recipients, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Nhập chi tiết" class="btn btn-default" />
            </div>
        </div>
    </div>
}

PHSach/Views/Bill_Export/Details.cshtml
@model PHSach.Models.Bill_Export

@{
    ViewBag.Title = "Details";
    var a = (List<PHSach.Models.Detail_Bill_Export>)ViewBag.ctpx;
}

<h2>Chi tiết phiếu xuất</h2>

    <a class="btn btn-primary btnThemPhieuXuat" href="~/Bill_Export/Index">Quay về</a>
    <hr />
    <table class="table" border="1">
        <tr>
            <th>
                Mã sách
            </th>
            <th>
                Số lượng
            </th>
            <th>
                Giá xuất
            </th>
            <th>
                Thành tiền
            </th>
        </tr>

        @foreach (var item in a)
        {
            <tr>
                <td>
                    @item.Book_id
                </td>
                <td>
                    @item.Quantity
                </td>
                <td>
                    @item.Cost
                </td>
                <td>
                    @item.Total
                </td>
            </tr>
        }

    </table>

PHSach/Views/Bill_Export/Index.cshtml
@model IEnumerable<PHSach.Models.Bill_Export>

@{
    ViewBag.Title = "DanhSachPhieuXuat";
}

<h2>Danh sách phiếu xuất</h2>

<p>
    <a class="btn btn-primary btnThemPhieuNhapp" href="~/Bill_Export/Create">Tạo phiếu xuất</a>
</p>
<table class="table" border="1">
    <tr>
        <th>
            Mã Phiếu Xuât
        </th>
        <th>
            Tên Đại Lý
        </th>
        <th>
            Người Nhận Hàng
        </th>
        <th>
            Ngày tạo phiếu
        </th>
        <th>
            Tổng Cộng
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Bill_Export_id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Agency.Agency_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Recipients)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Total)
        </td>
        <td>
            @Html.ActionLink("Chi tiết", "Details", new { id = item.Bill_Export_id })
        </td>
    </tr>
}

</table>

PHSach/Views/Bill_Export/ThemChiTietPhieuXuat.cshtml
@model PHSach.Models.Bill_Export

@{
    ViewBag.Title = "ThemChiTietPhieuXuat";
    var dsCtPx = (List<PHSach.Models.Detail_Bill_Export>)Session["ctphieuxuat"];
}

<h2>Thêm chi tiết phiếu xuất</h2>
<div class="x_content">
    @using (Html.BeginForm("ThemChiTietPhieuXuat", "Bill_Export", FormMethod.Post))
    {
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.AntiForgeryToken()
        <div class="form-group col-sm-10">
            <div class="col-sm-6">
                <label for="disabledInput">Mã sách</label>
                @Html.DropDownList("sach", null, htmlAttributes: new { @id = "masach", @name = "masach", @class = "form-control" })
                @*<input id="masach" name="masach" type="number" class="form-control col-md-7 col-xs-12" />*@
            </div>
        </div>
        <div class="form-group col-sm-10">
            <div class="col-sm-6">
                <label for="disabledInput">Số lượng</label>
                <input id="soluong" name="soluong" type="number" value="1" class="form-control col-md-7 col-xs-12" />
            </div>
        </div>
                            <div class="form-group">
                                
                                <div class="col-md-5 col-sm-5 col-xs-12 col-md-offset-3">
                                    <div class="form-group">
                                        <button id="next" type="submit" class="btn btn-primary" name="add">Thêm</button>
                                        <button id="next" class="btn btn-primary" name="create">Lưu phiếu</button>
                                        <a class="btn btn-primary btnThemPhieuXuat" href="~/Bill_Export/Index">Hủy phiếu</a>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <b style="color:red;">@ViewBag.loi</b>
                                </div>
                            </div>
                            <table id="chitiet" class="table table-striped table-bordered bulk_action">
                                <thead>
                                    <tr>
                                        <td>ID Sách</td>
                                        <td>Số lượng xuất</td>
                                        <td>Đơn giá xuất</td>
                                        <td>Tổng cộng</td>
                                        <td></td>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (dsCtPx != null)
                                    {
                                        foreach (var ct in dsCtPx)
                                        {
                                            <tr>
                                                <td>@ct.Book_id</td>
                                                <td>@ct.Quantity</td>
                                                <td>@ct.Cost</td>
                                                <td>@ct.Total</td>                                     
                                                <td>@Html.ActionLink("Xóa", "Deletectpx", new { bookid = @ct.Book_id },null)</td>                                                                                         
                                            </tr>
                                        }
                                    }         
                                </tbody>
                            </table>
    }
</div>