PHSach/Models/Report_Agency.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_Agency
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Report_Agency()
        {
            this.Detail_Report_Agency = new HashSet<Detail_Report_Agency>();
        }
    
        public int Report_id { get; set; }
        public Nullable<int> Agency_id { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Agency Agency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detail_Report_Agency> Detail_Report_Agency { get; set; }
    }
}

PHSach/Controllers/Report_AgencyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PHSach.Models;

namespace PHSach.Controllers
{
    public class Report_AgencyController : Controller
    {
        private PhatHanhSachEntities db = new PhatHanhSachEntities();

        // GET: Report_Agency
        public ActionResult Index()
        {
            var report_Agency = db.Report_Agency.Include(r => r.Agency);
                return View(report_Agency.ToList());
        }

        public ActionResult Deletectpx(int bookid)
        {
            var list = (List<Detail_Report_Agency>)Session["ctphieubaocao"];
            list.RemoveAll(p => p.Book_id == bookid);
            return RedirectToAction("ThemChiTietPhieuBaoCao");
        }
        // GET: Report_Agency/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Report_Agency report_Agency = db.Report_Agency.Find(id);
            var a = (from b in db.Detail_Report_Agency
                     where b.Report_id == id
                     select b).ToList();
            ViewBag.ctpbc = a;
            if (report_Agency == null)
            {
                return HttpNotFound();
            }
            return View(report_Agency);
        }

        public ActionResult Deletectpbc(int bookid)
        {
            var list = (List<Detail_Report_Agency>)Session["ctphieubaocao"];
            list.RemoveAll(p => p.Book_id == bookid);
            return RedirectToAction("ThemChiTietPhieuBaoCao");
        }

        // GET: Report_Agency/Create
        public ActionResult Create()
        {
            ViewBag.Agency_id = null;
            Report_Agency report_Agency = new Report_Agency();
            report_Agency = (Report_Agency)Session["PhieuBaoCao"];
            /*var lstAgencyid = (from c in db.Debt_Agency
                                where ! (from d in db.Debt_Agency
                                         where d.debt <= 0
                                         select d.Agency_id).Contains(c.Agency_id)
                                select c.Agency_id).Distinct().ToList();*/
            var lstAgencydb = db.Agencies;
            List<Debt_Agency> lstDebtAgency = new List<Debt_Agency>();
            foreach (Agency agen in lstAgencydb)
            {
                Debt_Agency debtdaily = db.Debt_Agency.OrderByDescending(m => m.id).FirstOrDefault(m => (m.Agency_id == agen.Agency_id));
                lstDebtAgency.Add(debtdaily);
            }

            List<Agency> lstAgencyUI = new List<Agency>();
            foreach (Debt_Agency debtdailyitem in lstDebtAgency)
            {
                if (debtdailyitem.debt > 0)
                {
                    Agency agenSelect = db.Agencies.SingleOrDefault(n => n.Agency_id == debtdailyitem.Agency_id);
                    lstAgencyUI.Add(agenSelect);
                }
            }
            ViewBag.Agency_id = new SelectList(lstAgencyUI, "Agency_id", "Agency_name");
            return View();
        }

        // POST: Report_Agency/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Report_id,Agency_id,Total_Quantity,CreatedDate")] Report_Agency report_Agency)
        {
            if (ModelState.IsValid)
            {
                report_Agency.CreatedDate = DateTime.Now;
               // var tempreportagency = report_Agency;
                Session["ctphieubaocao"] = new List<Detail_Report_Agency>();
                Session["PhieuBaoCao"] = report_Agency;
                return RedirectToAction("ThemChiTietPhieuBaoCao");
            }

            ViewBag.Agency_id = new SelectList(db.Agencies, "Agency_id", "Agency_name", report_Agency.Agency_id);
            return View(report_Agency);
        }


        [HttpGet]
        public ActionResult ThemChiTietPhieuBaoCao()
        {
            Report_Agency report_Agency = new Report_Agency();
            report_Agency = (Report_Agency)Session["PhieuBaoCao"];
            var lstBookid = (from b in db.Inventory_Agency
                                   where b.Agency_id == report_Agency.Agency_id
                                   select b.Book_id).Distinct().ToList();
            List<Book> lstBooks = new List<Book>();
            foreach(var item in lstBookid)
            {
                Book book = db.Books.SingleOrDefault(n => n.Book_id == item);
                lstBooks.Add(book);
            }
            ViewBag.sach = new SelectList(lstBooks, "Book_id", "Book_name");
            //var phieunhap = (Bill_Import)TempData["PhieuNhap"];
            return View();
        }

        [HttpPost]
        public ActionResult ThemChiTietPhieuBaoCao(FormCollection chitiet)
        {
            //
            Report_Agency report_Agency = new Report_Agency();
            report_Agency = (Report_Agency)Session["PhieuBaoCao"];
            var lstBookid = (from b in db.Inventory_Agency
                             where b.Agency_id == report_Agency.Agency_id
                             select b.Book_id).Distinct().ToList();
            List<Book> lstBooks = new List<Book>();
            foreach (var item in lstBookid)
            {
                Book book = db.Books.SingleOrDefault(n => n.Book_id == item);
                lstBooks.Add(book);
            }
            ViewBag.sach = new SelectList(lstBooks, "Book_id", "Book_name");
            //
            ViewBag.loi = null;
            if (Request.Form["add"] != null)
            {
                if (ModelState.IsValid)
                {
                    bool check = true;
                    foreach (var ctpbc in (List<Detail_Report_Agency>)Session["ctphieubaocao"])
                    {
                        if (ctpbc.Book_id == Int32.Parse(chitiet["sach"].ToString()))
                        {
                            check = false;
                            ViewBag.loi = "Đã tồn tại sách trong phiếu";
                            break;
                        }
                    }
                    if (check)
                    {
                        if (chitiet["sach"] == null)
                        {
                            ViewBag.loi = "Không tồn tại sách để báo cáo";
                            goto baoloi;
                        }
                        var sach = db.Books.Find(Int32.Parse(chitiet["sach"].ToString()));
                        int soluong = Int32.Parse(chitiet["soluong"].ToString());
                        Report_Agency idagency = (Report_Agency)Session["PhieuBaoCao"];                 
                        Inventory_Agency tonkhodaily = db.Inventory_Agency.OrderByDescending(m => m.id).FirstOrDefault(m => (m.Agency_id == idagency.Agency_id && m.Book_id == (int)sach.Book_id));
                        if (sach == null)
                        {
                            ViewBag.loi = "Mã sách không tồn tại";
                            goto baoloi;
                        }
                        else
                        {
                            if (tonkhodaily == null)
                            {
                                ViewBag.loi = "Không có tồn kho";
                                goto baoloi;
                            }
                            else
                            {
                                if(soluong > 0)
                                {
                                    if (soluong <= (tonkhodaily.deliver_quantity - tonkhodaily.repay_quantity))
                                    {
                                        Detail_Report_Agency ctpbc = new Detail_Report_Agency();
                                        ctpbc.Report_id = (db.Report_Agency.Max(u => (int?)u.Report_id) != null ? db.Report_Agency.Max(u => u.Report_id) : 0) + 1;
                                        ctpbc.Book_id = Int32.Parse(chitiet["sach"].ToString());
                                        ctpbc.quantity = Int32.Parse(chitiet["soluong"].ToString());
                                        //((List<Int32>)Session["BookID"]).Add(ctpbc.Book_id);
                                        ((List<Detail_Report_Agency>)Session["ctphieubaocao"]).Add(ctpbc);
                                    }
                                    else
                                    {
                                        ViewBag.loi = "Vượt quá số lượng báo cáo";
                                        goto baoloi;
                                    }
                                }
                                else
                                {
                                    ViewBag.loi = "Nhập số lượng lớn hơn 0";
                                    goto baoloi;
                                }
                                
                            }

                        }
                        return RedirectToAction("ThemChiTietPhieuBaoCao");
                    }
                    else
                    {
                        
                    }
                }
            }
            else if (Request.Form["create"] != null)
            {
                if (ModelState.IsValid)
                {
                    if (((List<Detail_Report_Agency>)Session["ctphieubaocao"]).Count == 0)
                    {
                        ViewBag.loi = "Không được để phiếu trống";
                        goto baoloi;
                    }
                    double tongTien = 0;
                    double? temptongtien = 0;
                    Report_Agency test = new Report_Agency();

PHSach/Views/Report_Agency/Create.cshtml
@model PHSach.Models.Report_Agency

@{
    ViewBag.Title = "Create";
}

<h2>Tạo phiếu báo cáo từ Đại Lý</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-horizontal">
        <hr /> 

        <div class="form-group col-sm-10">
            <div class="col-sm-6">
                <label for="disabledInput">Chọn Tên Đại Lý:</label>
                @Html.DropDownList("Agency_id", null, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Nhập chi tiết" class="btn btn-default" />
            </div>
        </div>
    </div>
}

PHSach/Views/Report_Agency/Details.cshtml
@model PHSach.Models.Report_Agency

@{
    ViewBag.Title = "Details";
    var a = (List<PHSach.Models.Detail_Report_Agency>)ViewBag.ctpbc;
}

<h2>Chi tiết phiếu báo cáo</h2>

<a class="btn btn-primary btnThemPhieuXuat" href="~/Report_Agency/Index">Quay về</a>
<hr />
<table class="table" border="1">
    <tr>
        <th>
            Mã sách
        </th>
        <th>
            Số lượng
        </th>
    </tr>

    @foreach (var item in a)
    {
        <tr>
            <td>
                @item.Book_id
            </td>
            <td>
                @item.quantity
            </td>
        </tr>
    }

</table>

PHSach/Views/Report_Agency/Index.cshtml
@model IEnumerable<PHSach.Models.Report_Agency>

@{
    ViewBag.Title = "Index";
}

<h2>Danh sách phiếu báo cáo</h2>

<p>
    <a class="btn btn-primary btnThemPhieuNhapp" href="~/Report_Agency/Create">Tạo phiếu báo cáo</a>
</p>
<table class="table" border="1">
    <tr>
        <th>
            Mã Phiếu Báo Cáo
        </th>
        <th>
            Tên Đại Lý
        </th>
        <th>
            Ngày tạo phiếu
        </th>
        <th>
            Tổng Cộng
        </th>
        <th></th>
    </tr>
    
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Report_id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Agency.Agency_name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Total)
                </td>
                <td>
                    @Html.ActionLink("Chi tiết", "Details", new { id = item.Report_id })
                </td>
            </tr>
        } 

</table>

PHSach/Views/Report_Agency/ThemChiTietPhieuBaoCao.cshtml
@model PHSach.Models.Report_Agency

@{
    ViewBag.Title = "ThemChiTietPhieuBaoCao";
    var dsCtPbc = (List<PHSach.Models.Detail_Report_Agency>)Session["ctphieubaocao"];
}

<h2>Thêm chi tiết phiếu báo cáo</h2>
<div class="x_content">
    @using (Html.BeginForm("ThemChiTietPhieuBaoCao", "Report_Agency", FormMethod.Post))
    {
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.AntiForgeryToken()
        <div class="form-group col-sm-10">
            <div class="col-sm-6">
                <label for="disabledInput">Mã sách</label>
                @Html.DropDownList("sach", null, htmlAttributes: new { @id = "masach", @name = "masach", @class = "form-control" })
                @*<input id="masach" name="masach" type="number" class="form-control col-md-7 col-xs-12" />*@
            </div>
        </div>
        <div class="form-group col-sm-10">
            <div class="col-sm-6">
                <label for="disabledInput">Số lượng</label>
                <input id="soluong" name="soluong" type="number" value="1" class="form-control col-md-7 col-xs-12" />
            </div>
        </div>
                            <div class="form-group">
                                
                                <div class="col-md-5 col-sm-5 col-xs-12 col-md-offset-3">
                                    <div class="form-group">
                                        <button id="next" type="submit" class="btn btn-primary" name="add">Thêm</button>
                                        <button id="next" class="btn btn-primary" name="create">Lưu phiếu</button>
                                        <a class="btn btn-primary btnThemPhieuBaoCao" href="~/Report_Agency/Index">Hủy phiếu</a>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <b style="color:red;">@ViewBag.loi</b>
                                </div>
                            </div>
                            <table id="chitiet" class="table table-striped table-bordered bulk_action">
                                <thead>
                                    <tr>
                                        <td>ID Sách</td>
                                        <td>Số lượng báo cáo</td>
                                        <td></td>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (dsCtPbc != null)
                                    {
                                        foreach (var ct in dsCtPbc)
                                        {
                                            <tr>
                                                <td>@ct.Book_id</td>
                                                <td>@ct.quantity</td>                                   
                                                <td>@Html.ActionLink("Xóa", "Deletectpbc", new { bookid = @ct.Book_id },null)</td>                                                                                         
                                            </tr>
                                        }
                                    }         
                                </tbody>
                            </table>
    }
</div>